### ISSUE TITLE
[Feature Request] Add support for playwright fixtures

### ISSUE THREAD

**Issue by zakhenry** [mbolotov/intellij-playwright#12]
First off, I have to say that I am really loving Maestro, keep up the great work!

I'm currently introducing [playwright fixtures](https://playwright.dev/docs/test-fixtures) to my workflow, and unfortunately this means that Maestro is unable to present the play buttons in the margin which is my primary workflow.

I'm guessing the plugin does something like finding usages of the `test` function imported from `@playwright/test`, however this doesn't work with fixtures as the test function import come from a local path instead.

I wonder if this can be fixed by adding a configuration panel to the plugin with a field to configure a regex that defines how the `test` function import should be matched?

**Comment by mbolotov** [comment]
Hi Zak!
thanks for the idea!
could you try this bundle:
[Maestro-1.2-EAP.zip](https://github.com/mbolotov/intellij-playwright/files/9425567/Maestro-1.2-EAP.zip)
I've added matching the `test` function by it's type, so the plugin now recognizes all the tests of the `TestType` type from `@playwright/test/types/test.d.ts`

**Comment by zakhenry** [comment]
Nice one! that works pretty much exactly as intended, one very minor (non blocking) issue though - the play button also appears alongside calls to member functions of the test object. I think the expected behavior would be to have only the direct invoke call of the test type to create a margin symbol

example here on line 14 - it doesn't make sense to play the timeout line:
<img width="677" alt="Screenshot 2022-08-30 at 12 17 47" src="https://user-images.githubusercontent.com/721513/187320965-60dc1f35-dd90-40f7-acd8-6d761c1356e7.png">

**Comment by mbolotov** [comment]
fixed in 1.2 version
