### ISSUE TITLE
Reference to Cypress in right-click menu of test runner results

### ISSUE THREAD

**Issue by josh-pendragon** [mbolotov/intellij-playwright#15]
Test runner results have a menu/hotkey option to "Show Cypress Screenshot"
![image](https://user-images.githubusercontent.com/40903404/194918597-abedfded-1d14-453d-8a79-63ed3f7168d2.png)

**Comment by mbolotov** [comment]
hmm, I'm unable to reproduce this with Maestro. 
Do you have the Cypress plugin installed?

**Comment by mbolotov** [comment]
Hi @josh-pendragon!
Have you been able to check if the Cypress plugin is installed in your IDE?

**Comment by josh-pendragon** [comment]
Hi @mbolotov , Sorry for the delayed response, I had issues with my github email settings. 
I did have the cypress plugin installed as well, I took it out and the issue went away. Sorry about that!
