### ISSUE TITLE
[Bug] Project base from Playwright configuration template is not using

### ISSUE THREAD

**Issue by alexandrchumakin** [mbolotov/intellij-playwright#16]
I need to set custom "Project base" that is different from project root (as we have monorepo with multiple apps). But every time when I start a new test via this plugin, it doesn't use a "Project base" from configuration template and I need to stop a test, open Run/Debug configuration and change it for every new test execution.

**Comment by alexandrchumakin** [comment]
Environment: Windows 10, WebStorm 2022.2.3

**Comment by mbolotov** [comment]
[Alexander](https://github.com/alexandrchumakin), you can try this bundle with the fix:
[Maestro-1.2-EAP2.zip](https://github.com/mbolotov/intellij-playwright/files/9763045/Maestro-1.2-EAP2.zip)

Also, could you please check if you can reproduce the problem described in #14?

**Comment by mbolotov** [comment]
this is strange that the project base is not set from the template.
it's working nice at my side. 

could you try this bundle:
[Maestro-1.2.1-EAP3.zip](https://github.com/mbolotov/intellij-playwright/files/9791854/Maestro-1.2.1-EAP3.zip)
I've added some additional logging. Please collect them and send me. You might want to mask the sensitive data within the logs.

**Comment by alexandrchumakin** [comment]
Thanks for this patch, I don't know whether you just added logs, but this version works for me just fine! I can't reproduce the issue anymore.
