### ISSUE TITLE
Anonymous describe is not handled by Maestro

### ISSUE THREAD

**Issue by yehuda-goose-miller** [mbolotov/intellij-playwright#17]
Per [Playwright documentation](https://playwright.dev/docs/release-notes#%EF%B8%8F-anonymous-describe) you can have an anonymous describe like
```
test.describe(()=> {
   ....
});
```

but Maestro does not recognize tests inside this block.

**Comment by mbolotov** [comment]
Hi Yehuda!
Thanks for the report!
I just checked the problem and found that Maestro does not indeed recognize an anonymous `describe` block itself, but it do recognize a `test` inside it:
![image](https://user-images.githubusercontent.com/19785715/196035473-bf0eb49a-12ff-45a8-8dcd-55fefb148d46.png)
Are you sure that you don't see the green arrow  at a test inside?

**Comment by mbolotov** [comment]
should be fixed in 1.3.1
