### ISSUE TITLE
30-day evaluation not providing valid license. 

### ISSUE THREAD

**Issue by josh-pendragon** [mbolotov/intellij-playwright#2]
After installing the plugin from the Webstorm plugins marketplace and initializing the 30-day evaluation, Webstorm throws the following errors on reload:

> 1 of 2 Exception in plugin Maestro (1.0.2)

[maestro-stacktrace1.txt](https://github.com/mbolotov/intellij-playwright/files/8043094/maestro-stacktrace1.txt)

[maestro-stacktrace2.txt](https://github.com/mbolotov/intellij-playwright/files/8043096/maestro-stacktrace2.txt)
[maestro-included2.txt](https://github.com/mbolotov/intellij-playwright/files/8043097/maestro-included2.txt)

[webstorm-info.txt](https://github.com/mbolotov/intellij-playwright/files/8043113/webstorm-info.txt)

**Comment by mbolotov** [comment]
Hi @josh-pendragon!
Sorry for the late answer. 
Do you still have the problem? I was unable to reproduce it on my side.

**Comment by josh-pendragon** [comment]
Hi. Just confirming that this is working for me now, thank you.
