### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by lavcraft** [mbolotov/intellij-playwright#27]
When run test:
```
/Users/$USER/.nvm/versions/node/v16.14.2/bin/npx playwright test --reporter /var/folders/9j/hwjc9f0s7nvg_fvkvzhrr4r00000gn/T/intellij-playwright-reporter921040841234507514.js src/api/api-create-conf.spec.ts -g ^(.*[\\\/])?api-create-conf.spec.ts.API: Create conference and related stuff - events, calls
env: node: No such file or directory
```

Why?

Node exists
/Users/$USER/.nvm/versions/node/v16.14.2/bin/npx — working in console and exists. What's wrong and how to fix this?

**Comment by mbolotov** [comment]
this might be an IntelliJ platform problem, see https://youtrack.jetbrains.com/issue/IDEABKL-7589 for details and workarounds.

**Comment by lavcraft** [comment]
Thanks, fix by run idea from terminal
