### ISSUE TITLE
How can I define the --config flag?

### ISSUE THREAD

**Issue by zakhenry** [mbolotov/intellij-playwright#6]
I use NX and so my tests are fairly nested within a folder. The npm script I run to get headed tests is

```sh
yarn playwright test --config ./apps/my-app-e2e/playwright.config.ts --headed
```

I don't have anything special in the config file, but I suspect the `testDir: './src/tests',` field is what is causing this plugin to fail to find my tests?

Out of the box if I try to run a test from the gutter I get 

<img width="533" alt="Screenshot 2022-05-03 at 04 15 30" src="https://user-images.githubusercontent.com/721513/166268767-d99d8f37-ad23-4f7a-ada9-6103aa82dc0b.png">

the console shows

```sh
/Users/zak/.nvm/versions/node/v14.17.1/bin/node /Users/zak/.nvm/versions/node/v14.17.1/lib/node_modules/yarn/bin/yarn.js run playwright test --reporter /var/folders/j8/hkdrcxfn7819nyspt0mqq0tm0000gn/T/intellij-playwright-reporter11570315857909753255.js optimize.spec.ts -g "^optimize.spec.ts.Optimize.should have the form initialised$"
yarn run v1.22.15
$ playwright test --reporter /var/folders/j8/hkdrcxfn7819nyspt0mqq0tm0000gn/T/intellij-playwright-reporter11570315857909753255.js optimize.spec.ts -g '^optimize.spec.ts.Optimize.should have the form initialised$'
```

nothing in that command has the relative path to the spec file so I think the config needs to be passed for discovery (or maybe the plugin can pass the full path directly?)

**Comment by mbolotov** [comment]
Hi Zak,
You can define any additional parameters in this field of a run configuration:
![image](https://user-images.githubusercontent.com/19785715/166309997-b8bf08bf-f2a2-4573-b546-1e7fc6232f70.png)

**Comment by zakhenry** [comment]
Wouldn't I need to do this on every test though? As in the workflow would be run test in margin, let it fail, go edit run configuration then rerun. for each test?

**Comment by mbolotov** [comment]
you can use run configuration templates to define default parameters to be used for a newly created configuration:
![image](https://user-images.githubusercontent.com/19785715/166311560-a0df3588-35b9-4230-b857-3506f965f976.png)

**Comment by zakhenry** [comment]
Oh fantastic, that works well thanks!

**Comment by rickirunge** [comment]
Also works if you manual change "Project Base" to the root of your project.

Don't know why this is set to the folder of the test being run - don't know when that would be needed? 
IMO it should (almost) always be the project root - the same ways as when you run playwright using "npm run"
